workflows:
  ios_testflight:
    name: iOS TestFlight
    instance_type: mac_mini_m2
    max_build_duration: 60

    integrations:
      app_store_connect: Codemagic

    environment:
      flutter: stable
      xcode: latest

      ios_signing:
        provisioning_profiles:
          - WhiteSails Remote app store
        certificates:
          - Apple Distribution

    scripts:
      - name: Flutter pub get
        script: flutter pub get

      - name: Generate iOS build files (safe)
        script: |
          flutter clean
          flutter pub get
          flutter build ios --release --no-codesign

      - name: Install CocoaPods (generate workspace)
        script: |
          cd ios
          pod repo update
          pod install
          cd ..

      - name: Set up code signing (target Runner project)
        script: xcode-project use-profiles --project ios/Runner.xcodeproj

      - name: Build IPA (Codemagic build-ipa, no plist)
        script: |
          xcode-project build-ipa \
            --project ios/Runner.xcodeproj \
            --scheme Runner

    artifacts:
      - "**/*.ipa"

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
