workflows:
  ios_testflight:
    name: iOS TestFlight
    instance_type: mac_mini_m2
    max_build_duration: 60

    integrations:
      app_store_connect: Codemagic

    environment:
      flutter: stable
      xcode: latest
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.whitesails.remote

    scripts:
      - name: Flutter pub get
        script: flutter pub get

      # Applies the provisioning profiles/certificates you've stored in Codemagic
      - name: Set up code signing
        script: xcode-project use-profiles

      - name: Build IPA (release)
        script: flutter build ipa --release

    artifacts:
      - build/ios/ipa/*.ipa

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
